### ISSUE TITLE
Where to get the APK?

### ISSUE THREAD

**Issue by IzzySoft** [WeAreFairphone/android_packages_apps_FairphoneLauncher3#2]
In the `README.md` you write the launcher is "available to everyone" – but I couldn't find an `.apk` anywhere. It's neither on F-Droid nor on Play. Would you mind attaching it to the corresponding release (in `releases/`)?

**Comment by TPS** [comment]
See the discussion I started from https://github.com/WeAreFairphone/android_packages_apps_FairphoneLauncher3/commit/663262c54cd31cb2bcbc8c141e05aed45de4fdfe#commitcomment-22599477 onwards.  It answers everything you asked.

**Comment by IzzySoft** [comment]
@TPS Couldn't see it writes about the `.apk` being attached to `releases/`, nor does it tell where a ready-to-use `.apk` can be found – so sorry, but it does *not* answering everything I asked. It just explains why it's not on F-Droid (yet), and why it won't go to Play (reasons I second). So while waiting to get into the official F-Droid repo, an attachment in `releases/` would be very welcome :wink:

**Comment by TPS** [comment]
> because its codebase needs to be adapted yet. It is tightly integrated into the system

I understand this to mean they're not comfortable releasing a standalone APK until they can de-couple this from the system more.

But I agree releasing a standalone APK is the end goal here. 😀

**Comment by IzzySoft** [comment]
Meaning if you'd attach an `.apk` of the current codebase here, that would only be able to run on a Fairphone? Confused how that goes along with "available to everyone" then (as opposed to "available to everyone who can solve the dependencies and build the APK", as the code is doubtless there).

**Comment by Roboe** [comment]
Well, "available to everyone" is the goal. But it takes time and, as you already figured out, it's not ready.
I'm attaching an insufficiently-tested `prealpha` APK to [releases](https://github.com/WeAreFairphone/android_packages_apps_FairphoneLauncher3/releases/tag/2.0.0)

**Comment by IzzySoft** [comment]
Thanks, @Roboe ! Just wondering, as there's one "green" release: would it make sense to attach that APK as well (and continue doing so at least for "stable ones")?

**Comment by Roboe** [comment]
The version tagged `1.0.0` you refer to has the signature `com.fairphone.fplauncher3`, not the `community.fairphone.fplauncher3`), and Fairphone asked us [not to use the `com.fairphone.*` prefix](https://github.com/WeAreFairphone/android_packages_apps_MyContactsWidget/issues/4).

It also causes permission conflicts with other preshipped launchers (the AOSP's Launcher3 and LineageOS's Trebuchet) when installing it.

Differences with the `2.0.0` pre-release are that packagename change and the permission fix, so&hellip; it doesn't has any sense, really
