### ISSUE TITLE
Conflicting permissions

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/android_packages_apps_FairphoneLauncher3#6]
Hello,

This app can't be installed on Fairphone OS:
```
Package community.fairphone.fplauncher3 attempting to redeclare permission com.android.launcher3.permission.RECEIVE_FIRST_LOAD_BROADCAST already owned by com.fairphone.fplauncher3
```

Or on LineageOS:
```
Package community.fairphone.fplauncher3 attempting to redeclare permission com.android.launcher3.permission.RECEIVE_FIRST_LOAD_BROADCAST already owned by com.cyanogenmod.trebuchet
```
(And probably on some other Android ROMs too.)

This is because the `com.android.launcher3.permission.*` permissions are already used by most default launchers (because most of them are forks of the AOSP launcher).

Would it be possible to rename the permissions to something else?

**Comment by Roboe** [comment]
Hey, thank you for adding the app to the F-Droid repo. As you can observe, we are not actively maintaining these Fairphone apps's repos for a while.

As you look interested in improving them, I invited you to join the organization into the @WeAreFairphone/features-maintainers team. Feel free to work on them (including #5), but keep opening issues for every matter and work with PRs &mdash;that way we can keep being informed with changes and eventualy join you or help with some. Welcome! :smiley:

**Comment by ildar** [comment]
Good to see the fix is ready. Please ETA to F-Droid? Thanks!
